version: '2'
services:
  aria2:
    image: ihciah/aria2
    container_name: aria2
    ports:
      - "16800:6800"
    volumes:
      - /mnt/common-blk/shared:/data
      - /mnt/common-blk/aria2-data:/aria2-data
      - ../conf:/etc/aria2:ro
    restart: always
    logging:
      driver: "none"

