version: '2'
services:
  overture:
    image: ihciah/overture
    container_name: overture
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./overture:/etc/overture:ro
    restart: always

